---

# redis is available on port 6379 by default
- name: install redis in-memory database
  apt:
    pkg: redis-server

- name: declare an init system to manage redis as a service
  replace:
    path: /etc/redis/redis.conf
    regexp: '^supervised no*'
    replace: 'supervised systemd'
  notify: restart redis

- name: create directory to store redis override.conf
  file:
    path: /etc/systemd/system/redis-server.service.d
    state: directory
    owner: root
    group: root

- name: create override.conf to fix systemd start file for redis
  copy:
    dest: /etc/systemd/system/redis-server.service.d/override.conf
    content: |
      [Service]
      Type=notify
  notify: systemctl daemon-reload

- name: ensure redis is enabled and restarted
  service:
    name: redis
    enabled: yes

- name: set redis listen address
  replace:
    path: /etc/redis/redis.conf
    regexp: '^bind .*$'
    replace: "bind {{ redis_listen_address }}"
  notify: restart redis

- name: set redis listen port
  replace:
    path: /etc/redis/redis.conf
    regexp: '^port .*$'
    replace: "port {{ redis_listen_port }}"
  notify: restart redis

# Redis optimization (not working on LXD!!!)
# Transparent Huge Pages (THP) support is enabled by default in kernel. This will create latency and memory usage issues with Redis. 
#- name: disable Transparent Huge Pages (THP) support in kernel
  #shell: |
    #echo never > /sys/kernel/mm/transparent_hugepage/enabled
    #touch disable-thp.done
  #args:
    #creates: disable-thp.done
  #notify: restart redis

#- name: disable Transparent Huge Pages (THP) support in kernel at reboot
  #copy:
    #dest: /etc/rc.local
    #content: |
      ##!/bin/sh -e
      #echo never > /sys/kernel/mm/transparent_hugepage/enabled
      #exit 0
    #mode: '0755'

#- name: set vm.overcommit_memory = 1
  #sysctl: 
    #name: vm.overcommit_memory
    #value: '1'
    #sysctl_set: yes
    #state: present
    #reload: yes

# TODO secure redis?
