---

- name: install required postgresql packages for ansible
  apt:
    pkg:
      - python-psycopg2
      - python3-psycopg2

- name: check if decidim database is present
  postgresql_query:
    db: postgres
    query: "SELECT 1 from pg_database WHERE datname='{{ db_name }}';"
    login_host: "{{ db_server }}"
    login_user: "{{ db_user }}"
    login_password: "{{ db_pass }}"
  register: decidim_db_check_exist

- name: create decidim database on server {{ db_server }} and initialize it
  shell: |
      . $HOME/.rubyrc
      bin/rails db:create RAILS_ENV={{ deployment_environment }}
  args:
    chdir: "{{ decidim_home }}/{{ decidim_app_dir }}"
  when: decidim_db_check_exist.rowcount == 0
  become: yes
  become_user: "{{ decidim_user }}"

- name: rake db migrate
  shell: |
    . $HOME/.rubyrc
    bin/rake db:migrate RAILS_ENV={{ deployment_environment }}
  args:
    chdir: "{{ decidim_home }}/{{ decidim_app_dir }}"
  become: yes
  become_user: "{{ decidim_user }}"
