---

- name: get nodejs install repo script
  get_url:
    url: "https://deb.nodesource.com/setup_{{ nodejs_version }}.x"
    dest: "/root/setup_{{ nodejs_version }}.x"
    mode: '755'

- name: create nodejs package repo
  shell: "/root/setup_{{ nodejs_version }}.x"
  args:
    creates: /etc/apt/sources.list.d/nodesource.list

- name: install nodejs version {{ nodejs_version }} and imagemagick packages
  apt:
    pkg:
      - nodejs
      - imagemagick
