---

# fix yarn not installed warning (https://yarnpkg.com/lang/fr/docs/install/#debian-stable)
- name: get public key for yarn repo
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present

- name: add yarn package repo
  apt_repository:
    repo: 'deb https://dl.yarnpkg.com/debian/ stable main'
    state: present

- name: install yarn package
  apt:
    pkg: yarn
    update_cache: yes
