---
# playbook file to set up the machine and install Decidim

- name: Provision the server on Hetzner
  hosts: localhost
  connection: local
  gather_facts: True
  vars:
    override_default_file: "{{ lookup('first_found', 'custom_settings/vars.yml', errors='ignore') }}"
  roles:
    - role: common_settings
    - role: hetzner
    - role: gandi
    - role: matomo
    - role: sentry

- hosts: server
  vars:
    override_default_file: "{{ lookup('first_found', 'custom_settings/vars.yml', errors='ignore') }}"
  roles:
    - role: common_settings
    - role: init_container
    - role: geerlingguy.clamav
    - role: postgresql
    - role: redis
    - role: decidim
