---
# handlers file for redis

- name: stop snap redis
  command: snap stop redis.server
  changed_when: false

- name: restart redis
  service:
    name: redis
    state: restarted

- name: systemctl daemon-reload
  shell: systemctl daemon-reload
  notify:
    - stop snap redis
    - restart redis
