---
# handlers file for redis

- name: ensure snap does not interfere
  command: snap stop redis.server
  changed_when: false

- name: restart redis
  service:
    name: redis
    state: restarted

- name: systemctl daemon-reload
  shell: systemctl daemon-reload
  notify: restart redis
