---
# tasks file for init_container

- when: override_default_file is file
  include_vars: "{{ override_default_file }}"

- name: Get facts from local roles
  set_fact:
    matomo_site_id: "{{ hostvars['localhost'].matomo_site_id }}"
    sentry_dsn: "{{ hostvars['localhost'].sentry_dsn }}"

- name: upgrade all packages in container
  apt:
    update_cache: yes
    upgrade: yes
  when: ansible_distribution == 'Ubuntu'

- name: remove old packages
  apt:
    autoremove: yes
  when: ansible_distribution == 'Ubuntu'

- name: upgrade all packages in container
  yum:
    name: '*'
    state: 'latest'
  when: ansible_distribution == 'Centos'

- name: set machine timezone to "{{ timezone }}"
  timezone:
    name: "{{ timezone }}"

- name: ensure journalctl will not eat whole disk
  replace:
    path: /etc/systemd/journald.conf
    regexp: '^#SystemMaxUse.*'
    replace: "SystemMaxUse=100M"

- name: restart journald
  become: true
  systemd: name=systemd-journald state=restarted
