---
# tasks file for init_container

- when: override_default_file is file
  include_vars: "{{ override_default_file }}"

- name: Get facts from local roles
  set_fact:
    matomo_site_id: "{{ hostvars['localhost'].matomo_site_id }}"
    sentry_dsn: "{{ hostvars['localhost'].sentry_dsn }}"

- name: Remove apt lock files
  file: path={{ item }} state=absent
  with_items:
    - /var/lib/apt/lists/lock
    - /var/cache/apt/archives/lock
    - /var/lib/dpkg/lock-frontend

- name: install ca-certificates
  apt:
    pkg: ca-certificates
    update_cache: yes

- name: upgrade all packages in container
  apt:
    update_cache: yes
    upgrade: yes

- name: remove old packages
  apt:
    autoremove: yes
  when: ansible_distribution == 'Ubuntu'

- name: set machine timezone to "{{ timezone }}"
  timezone:
    name: "{{ timezone }}"

- name: ensure journalctl will not eat whole disk
  replace:
    path: /etc/systemd/journald.conf
    regexp: '^#SystemMaxUse.*'
    replace: "SystemMaxUse=100M"

- name: restart journald
  become: yes
  systemd: name=systemd-journald state=restarted
