---

- when: override_default_file is file
  include_vars: "{{ override_default_file }}"

- name: Check if website already exists on Matomo
  uri:
    url: "{{ matomo_server_address }}"
    method: POST
    status_code: 200
    body_format: form-urlencoded
    body:
      module: API
      format: json
      token_auth: "{{ matomo_write_token }}"
      method: SitesManager.getSitesIdFromSiteUrl
      url: "https://{{ domain }}"
  register: response
  become_user: True

- name: Create new website on Matomo
  uri:
    url: "{{ matomo_server_address }}"
    method: POST
    status_code: 200
    body_format: form-urlencoded
    body:
      module: API
      format: json
      token_auth: "{{ matomo_write_token }}"
      method: SitesManager.addSite
      siteName: "decidim-{{ app_name }}"
      urls[0]: "https://{{ domain }}"
      timezone: "{{ timezone }}"
  become_user: True
  register: created
  when: (response.json | length == 0)

- set_fact:
    idSite: "{{ response.json[0].idsite if (response.json | length > 0) else created.json.value }}"

- name: Give view access to decidim user
  uri:
    url: "{{ matomo_server_address }}"
    method: POST
    status_code: 200
    body_format: form-urlencoded
    body:
      module: API
      format: json
      token_auth: "{{ matomo_write_token }}"
      method: UsersManager.setUserAccess
      userLogin: "{{ matomo_view_user }}"
      access: view
      idSites: "{{ idSite }}"
  become_user: True
  when: (response.json | length == 0)

- name: Update existing website on Matomo
  uri:
    url: "{{ matomo_server_address }}"
    method: POST
    status_code: 200
    body_format: form-urlencoded
    body:
      module: API
      format: json
      token_auth: "{{ matomo_write_token }}"
      method: SitesManager.updateSite
      idSite: "{{ idSite }}"
      siteName: "decidim-{{ app_name }}"
      urls[0]: "https://{{ domain }}"
      timezone: "{{ timezone }}"
  become_user: True
  when: (response.json | length > 0)

- set_fact:
     matomo_site_id: "{{ idSite }}"
     delegate_to: "{{ server.hcloud_server.ipv4_address }}"
     delegate_facts: true
